export enum EReportType {
  TotalSales           = 'total_sales',
  CashSales            = 'cash_sales',
  CreditSales          = 'credit_sales',
  TotalBills           = 'total_bills',
  AverageBillValue     = 'average_bill_value',
  TimeWiseSales        = 'time_wise_sales',
  TopSellingProducts   = 'top_selling_products',
  SlowMovingProducts   = 'slow_moving_products',

  TotalExpense         = 'total_expense',
  ShopExpense          = 'shop_expense',
  OtherExpense         = 'other_expense',
  OpeningCash          = 'opening_cash',
  ClosingCash          = 'closing_cash',
  TotalPurchase        = 'total_purchase',
  PurchaseReturn       = 'purchase_return',
  TotalProfit          = 'total_profit',
  NetProfit            = 'net_profit',

  ClosingStock         = 'closing_stock',
  LowStockItems        = 'low_stock_items',
  OutOfStockItems      = 'out_of_stock_items',
  DamagedStock         = 'damaged_stock',
  ReturnedItems        = 'returned_items',

  TotalCustomers       = 'total_customers',
  NewCustomers         = 'new_customers',
  RepeatCustomers      = 'repeat_customers',
  CreditGiven          = 'credit_given',
  CreditReceived       = 'credit_received',
  PendingCredit        = 'pending_credit',

  SupplierPayment         = 'supplier_payment',
  PendingSupplierPayment  = 'pending_supplier_payment',
  StaffAttendance         = 'staff_attendance',
  WeeklyComparison        = 'weekly_comparison',
}

export const REPORT_TYPE_LABELS: Record<EReportType, string> = {
  [EReportType.TotalSales]:           'Total Sales',
  [EReportType.CashSales]:            'Cash Sales',
  [EReportType.CreditSales]:          'Credit Sales',
  [EReportType.TotalBills]:           'Total Bills',
  [EReportType.AverageBillValue]:     'Average Bill Value',
  [EReportType.TimeWiseSales]:        'Time-wise Sales',
  [EReportType.TopSellingProducts]:   'Top Selling Products',
  [EReportType.SlowMovingProducts]:   'Slow Moving Products',
  [EReportType.TotalExpense]:         'Total Expense',
  [EReportType.ShopExpense]:          'Shop Expense',
  [EReportType.OtherExpense]:         'Other Expense',
  [EReportType.OpeningCash]:          'Opening Cash',
  [EReportType.ClosingCash]:          'Closing Cash',
  [EReportType.TotalPurchase]:        'Total Purchase',
  [EReportType.PurchaseReturn]:       'Purchase Return',
  [EReportType.TotalProfit]:          'Total Profit',
  [EReportType.NetProfit]:            'Net Profit',
  [EReportType.ClosingStock]:         'Closing Stock',
  [EReportType.LowStockItems]:        'Low Stock Items',
  [EReportType.OutOfStockItems]:      'Out of Stock Items',
  [EReportType.DamagedStock]:         'Damaged Stock',
  [EReportType.ReturnedItems]:        'Returned Items',
  [EReportType.TotalCustomers]:       'Total Customers',
  [EReportType.NewCustomers]:         'New Customers',
  [EReportType.RepeatCustomers]:      'Repeat Customers',
  [EReportType.CreditGiven]:          'Credit Given',
  [EReportType.CreditReceived]:       'Credit Received',
  [EReportType.PendingCredit]:        'Pending Credit',
  [EReportType.SupplierPayment]:      'Supplier Payment',
  [EReportType.PendingSupplierPayment]: 'Pending Supplier Payment',
  [EReportType.StaffAttendance]:      'Staff Attendance',
  [EReportType.WeeklyComparison]:     'Weekly Comparison',
};
